### ISSUE TITLE
Gathering Information

### ISSUE THREAD

**Issue by Sanchik228** [Sanchik228/SETestRepository#4]
Subtasks:
- [ ] #2 Implement the calculate function.
- [ ] #2  Handling exceptions for calculate
- [ ] #2  Testing the calculate function
